### ISSUE TITLE
"Copy selected value from NNN» action doesn’t copy anything (Safari)

### ISSUE THREAD

**Issue by iromeo** [ctlab/phantasus#110]
MacOS 10.14
Version 12.0 (14606.1.36.1.9)
* Copy something to clipboard
* Open https://artyomovlab.wustl.edu/phantasus/
* "GSE65067"
* Select first 5 rows and copy selected value from id
![image](https://user-images.githubusercontent.com/72933/52272266-523af580-2957-11e9-9a87-b98703d43af0.png)
* Paste action (Meta+C or using context menu) inserts value from the first step

**Comment by vlakam** [comment]
Seems like fixed in phantasus.js/develop.

**Comment by assaron** [comment]
@iromeo can you check that the fix works for you at https://genome.ifmo.ru/phantasus-dev/ ?

**Comment by iromeo** [comment]
@assaron thanks, works now
