### ISSUE TITLE
Make boxplot chart as default instead of row profile

### ISSUE THREAD

**Issue by shashj** [ctlab/phantasus#114]
Row profile plot is very slow for large datasets, instead, boxplot can be made as default which is fast or we don't show any plot by default.

**Comment by vlakam** [comment]
Hi there.

We made some enchancements regarding this issue. You see, making boxplot default is actually not a solution to a problem. Changes in current development build gonna make experience smoother by disabling profiles when more than 100 genes are chosen and leaving this matter to user concern (like in scenario where only mean\median profile is needed).

While we are at, the issue will remain opened, so feel free to express your opinion about the problem and new "feature".

Stay tuned.

**Comment by vlakam** [comment]
Looks cool

**Comment by shashj199** [comment]
Is it done @vlakam ?

**Comment by vlakam** [comment]
Current master implements behavior described in my previous post. If you have any ideas feel free to comment this issue
