### ISSUE TITLE
How to use fgsea?

### ISSUE THREAD

**Issue by shashj** [ctlab/phantasus#115]
Hi, I am very much interested to use fgsea in phantasus. I understand that we need to provide fgsea meta files, how do we provide them? A little help and direction will be of huge help.

Thanks

**Comment by vlakam** [comment]
Hi.

You need to generate list with columns ("geneID", "pathName", "geneSymbol") and place it under cacheDir/fgsea in .rds format

**Comment by shashj** [comment]
@vlakam Thank you so much it works. Just a question, if I click on some pathway to check the genes it throws some error

![Screen Shot 2019-04-06 at 12 01 44 AM](https://user-images.githubusercontent.com/22262181/55648933-3b9e0700-57ff-11e9-9f16-ce6cd10afe8a.png)

**Comment by shashj** [comment]
@vlakam Don't worry I figured it out, we have to give gene symbols as well
