### ISSUE TITLE
Permanent link should restore the operations on the datasets 

### ISSUE THREAD

**Issue by shashj** [ctlab/phantasus#116]
Right now permanent link only opens up the dataset. What would be really cool if the entire state of phantasus is restored such as hierarchical clustering and colouring? I don't know if this is possible already.

**Comment by vlakam** [comment]
Hi.

It's not possible at the moment.

**Comment by vlakam** [comment]
Hello.
Current develop branch support the described feature. 
Yet still no ETA about merging into master

**Comment by shashj** [comment]
Thanks a ton, this is really helpful.
