### ISSUE TITLE
Link RNASeq datasets to phantasus using dee2

### ISSUE THREAD

**Issue by shashj199** [ctlab/phantasus#123]
Hi,

As I understand that phantasus can use ARCHS4 for RNA-Seq datasets. There is a recent publication which massively aligns a lot of samples from GEO. Here is the link: http://dee2.io/

Here is the publication: https://academic.oup.com/gigascience/article/8/4/giz022/5426567

Can we connect this to phantasus?

Thanks a lot

@assaron

**Comment by assaron** [comment]
Thanks for the link. Is there any specific dataset available here and not in ARCHS4? 

Still, the format they use is not that easy to integrate (big tsv table), so I'm not sure we do it soon. I'll keep the issue open.

**Comment by shashj199** [comment]
Yeah, ARCHS4 is relatively smaller than dee2 dataset, it would be good to have a bigger repository as part of phantasus. I can check if we can convert it to a usable format but I will not be able to integrate it with phantasus since I am not familiar with javascript, so if you can guide me on the format, I might be able to help out.

**Comment by assaron** [comment]
The integration happens on the R back-end. The function for ARCHS4 is pretty small: https://github.com/ctlab/phantasus/blob/master/R/loadGEO.R#L170 

If you can convert it to the h5 format indexed by GSM ids, it will be pretty straightforward to make it work.

**Comment by shashj199** [comment]
Great thanks, will look into it.

**Comment by assaron** [comment]
Close in favor of #73
