### ISSUE TITLE
Broken Travis

### ISSUE THREAD

**Issue by saksham219** [ctlab/phantasus#147]
The docker build on Travis seems to be causing problems for deployment. 
https://travis-ci.org/ctlab/phantasus/jobs/628124291?utm_medium=notification&utm_source=github_status

**Comment by assaron** [comment]
This happens sometimes for random reasons. I rebuild started the rebuild and everything went OK

**Comment by saksham219** [comment]
Hi @assaron . It seems like appveyor is failing because of bioconductor not getting installed
https://ci.appveyor.com/project/assaron/phantasus-puawl

Anyway, I do not see the plot option both [here](https://ctlab.itmo.ru/phantasus/) and [here](https://artyomovlab.wustl.edu/phantasus/). Are these the sites where phantasus is deployed?

**Comment by assaron** [comment]
Currently it's deployed in our test site: https://ctlab.itmo.ru/phantasus-dev/ I'll deploy it to the other versions as well, if there are no problems
