### ISSUE TITLE
Sweep runs but gives non-numeric error

### ISSUE THREAD

**Issue by saksham219** [ctlab/phantasus#150]
![image](https://user-images.githubusercontent.com/28567402/71664536-4d590e80-2d7f-11ea-87c4-dd4d20a34212.png)

Probably this is because the target in sweep call is being read as character vector

**Comment by assaron** [comment]
I can't reproduce the error, but hope it is fixed now, as we've update annotation type handling (currently deployed only on https://ctlab.itmo.ru/phantasus-dev/)
