### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by Celia5** [ctlab/phantasus#157]
I receive a Proxy Error every time I try to run an FGSEA on my RNA-seq data. When I analyzed this data using phantasus several months ago there was no issue. I have tried running the FGSEA on different computers, browsers, wifi networks, etc but keep getting this error:

Failed to perform FGSEA. Error:
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /phantasus/ocpu/library/phantasus/R/performFGSEA/print.
Reason: Error reading from remote server
________________________________________
Apache/2.4.18 (Ubuntu) Server at artyomovlab.wustl.edu Port 443

**Comment by assaron** [comment]
That's very strange. Can you please do the following:
1. Open https://artyomovlab.wustl.edu/phantasus/?preloaded=GSE53986.Ctrl.vs.LPS 
2. Run FGSEA with *MSigDB Hallmarks - Mus Musculus (Entrez)* as pathway database, *t* as statistics and *Gene ID* as column with Gene IDs.

If it fails, please do the same for https://artyomovlab.wustl.edu/phantasus-dev/?preloaded=GSE53986.Ctrl.vs.LPS and for https://ctlab.itmo.ru/phantasus/?preloaded=GSE53986.Ctrl.vs.LPS

**Comment by Celia5** [comment]
Hello,

When I try to run the FGSEA using the datasets you provided, it works just fine.

However when I try it on my dataset (either as a .gct or starting fresh from importing the original .tsv file) I receive either a "504 gateway timeout" error if I try using entrezgene or ensemble geneIDs as the Gene ID column, or a "FGSEA returned 0 rows. Nothing to show" error if I use the gene name.  These are human genes but when I ran FGSEA a few months ago using the "gene name"  it worked just fine using various databases.

________________________________

**Comment by assaron** [comment]
Ok, can you attach the dataset? If you don't want to make it public, you can send it to my e-mail (alsergbox@gmail.com)

**Comment by assaron** [comment]
The issue has been resolved
