### ISSUE TITLE
problem with DESeq2

### ISSUE THREAD

**Issue by JoelHaas** [ctlab/phantasus#162]
Hi, we recently upgraded to v1.21.3 and are now getting an error when we run DESeq2 (dataset is not defined). We get that starting from a previously saved session where we had already successfully run DESeq2, or starting from the raw data and re-annotating the columns for DE analysis.

I made sure we were updated to Bioconductor 3.17, R 4.3. This is on our internal server running ubuntu 20.04. For the time being, I'll try to downgrade and see which version works again.

**EDIT** : I also checked on the artyomov lab mirror and it also doesn't work.

**Comment by clevermx** [comment]
Fixed in v1.21.5.
