### ISSUE TITLE
createES function is not found in the package. 

### ISSUE THREAD

**Issue by uhatikus** [ctlab/phantasus#165]
For some reason, `createES` function is not found in the package `phantasus`. 

Example of behavior with the error:
https://rdrr.io/bioc/phantasus/man/createES.html

Error: 
```
Setting options('download.file.method.GEOquery'='auto')
Setting options('GEOquery.inmemory.gpl'=FALSE)
Loading config from /usr/lib/R/site-library/opencpu/config/defaults.conf
Error in createES(data, pData, varLabels, fData, fvarLabels, eData) : 
  could not find function "createES"
Execution halted
```

I have experienced the same behavior when I used `phantasus` locally:

<img width="800" alt="image" src="https://github.com/ctlab/phantasus/assets/12616388/251e6859-f623-4a72-a4fb-2a4bb33e0024">

**Comment by assaron** [comment]
Hi,

Could you please provide more context on how did you get the first error? `createES` is an internal function and is not exported, so that the behavior on the last screenshot is expected, it's available only as `phantasus:::createES`. However, it should not prevent it to be called within the Phantasus application, which apparently happens when you get the first error.

**Comment by uhatikus** [comment]
I have run the example on https://rdrr.io/bioc/phantasus/man/createES.html:
<img width="1139" alt="image" src="https://github.com/ctlab/phantasus/assets/12616388/b2217092-402f-4190-a709-9113d4893cab">

**Comment by assaron** [comment]
Ah, I see. `createES` is internal function and the corresponding documentation and examples are only for internal usage and aren't supposed to be run manually. Actually we need to add "internal" tag for this, so not to confuse users.

Anyway, if you want to open specifically prepared dataset from R you can prepare it as an `ExpressionSet` object and either save it to a GCT file with `write.gct` function and load it from the web-interface, or save it to and rda format and put it to the preloaded folder as described at https://ctlab.github.io/phantasus-doc/installation.html#preloaded-datasets

**Comment by uhatikus** [comment]
@assaron Thanks a lot! 
I will use the guide you sent me! 

Lasttly, I would like to mention that `createES` also exists in pdf manual: https://www.bioconductor.org/packages/devel/bioc/manuals/phantasus/man/phantasus.pdf (maybe here it is also mentioned for internal usage)
