### ISSUE TITLE
Some datasets have no annotation

### ISSUE THREAD

**Issue by assaron** [ctlab/phantasus#52]
Opening GSE43908 results in a dataset without any feature annotation. As a work-around gene_assignment column can be displayed. Later it can be parsed to gene ID and gene symbol.

**Comment by avkitex** [comment]
Same with GSE19417 (probes are numbers)
This may help you btw  =)
[GPL4372.txt](https://github.com/ctlab/phantasus/files/1214754/GPL4372.txt)

**Comment by baba-beda** [comment]
@avkitex 
What feature annotation do you expect to see for that dataset exactly? Right now there is "Gene Symbol" and "Gene ID". Which columns are required additionally?

**Comment by avkitex** [comment]
As far as I concerned GPL4372 probes look like numbers
Thus phantasus (current docker version) (or morpheus) may even fail to load dataset or display probe ids

Also this platform has no gene symbol annotation (see GSE19417)
I've annotated probes using mygene and created 3col file for this platform (see comment above)
This could help you to display Gene symbol for this platform

**Comment by assaron** [comment]
@avkitex You probably have cached versions of GSE19417 and/or GPL4372 files. Try to remove the files from the cache and reload the dataset. Current docker version works fine (see screenshot from artyomovlab.wustl.edu/phantasus
![2017-08-24-215618_1920x1080_scrot](https://user-images.githubusercontent.com/1040217/29683487-396783d4-8917-11e7-82c4-14dd4d1a490f.png)

**Comment by avkitex** [comment]
Ok, my bad. Maby I've confused with morpheus. And I had no chanse to compare with phanthasus as it was down fow few days
