### ISSUE TITLE
Opening GEO dataset shouldn't be available for annotate rows/columns action

### ISSUE THREAD

**Issue by assaron** [ctlab/phantasus#55]
1. Open any dataset.
2. File -> Open. 
3. Select "Open file action" to be "Annotate columns".

In "open your own file" dropdown menu there is option for opening GEO dataset, which doesn't make sense for this use case.

**Comment by assaron** [comment]
Probably, this should wait for merge with morpheus upstream, where there is a change in UI for opening files.

**Comment by vlakam** [comment]
Fixed in 1.1.4
