### ISSUE TITLE
The last name used to rename a tab "sticks around"

### ISSUE THREAD

**Issue by hpages** [ctlab/phantasus#82]
After renaming an **intermediate** tab (let's say I renamed the 2nd to last tab "tmp"), from now on it seems that all newly created tabs (automatically or explicitely with Ctrl+X) will be named "tmp". For example if I go back to the last tab right after renaming the intermediate tab (I didn't rename the last tab so it still has automatic name "GSE53986") and do Ctrl+X, it creates a new tab named "tmp".

**Comment by vlakam** [comment]
Cannot reproduce by this steps:
1. Open GSE53986
2. Make second tab by CTRL+X
3. Rename second tab to anything but original
4. Go back to first tab and make another one by CTRL+X.

Could you please share more info about the steps to repoduce + your browser info
