### ISSUE TITLE
Compatibility with GENE-E

### ISSUE THREAD

**Issue by kesaulova** [ctlab/phantasus#96]
For the sake of compatibility with GENE-E, is it possible to add these features:

- [ ] 1. Ability to create custom order of conditions for sorting (not alphabetical)
- [ ] 2. Ability to save chart as pdf/png (for my knowledge, I can save only heatmap)
- [ ] 3. Ability to color chart with conditions too (with what is now marked as "axis labels")
- [ ] 4. Is it possible to add adjustment to chart, like in GENE-E, to not do adjustment of whole dataset?

Thank you!

**Comment by assaron** [comment]
Closing in favor of #100 #101 and #102
